### ISSUE TITLE
2.1.54 - editor broken?

### ISSUE THREAD

**Issue by ijgnd** [kleinerpirat/anki-tooltips#2]
I installed the latest add-on version from today (2023-02-16) in 2.1.54. Your add-on is the only active one.

At the moment the add-on seems to collapse all fields in my editor so that it's not useable.

I attached a screenshot showing two overlapping windows. The editor is on the top in the background, at the bottom is the window showing my add-ons installed:

![image](https://user-images.githubusercontent.com/40218852/219293674-9f08530b-31fc-41b3-b18a-cd4c3d88e9b3.png)

**Comment by kleinerpirat** [comment]
Thank you for the report. I was too keen on getting this out to test whether the APIs I'm using are available on all supported versions.

I already fixed the error for 2.1.54. Solving it for versions until 2.1.50 should be possible too, it's just a bit more involved. Expect an update tonight.

**Comment by kleinerpirat** [comment]
The next release is compatible with 2.1.50 - 2.1.58+.
